export const CONSULTA_CITA_SUCCESS = 'CONSULTA_CITA_SUCCESS';
export const CONSULTA_CITA_ERROR = 'CONSULTA_CITA_ERROR';

export const CONSULTA_VETERINARIO_SUCCESS = 'CONSULTA_VETERINARIO_SUCCESS';
export const CONSULTA_VETERINARIO_ERROR = 'CONSULTA_VETERINARIO_ERROR';